# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - uacc-bff-api(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - Api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v4

    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '21.x'

    - name: npm install
      run: npm install

    - name: npm build
      run: npm run build

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v3
      with:
        app-name: uacc-bff-api
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_UACC }}
        package: .

